## Python list comprehensions

#### Syntax:
#### newlist = [expression for item in iterable if condition == True]

In [1]:
# a good and simple example
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

new_list = [x for x in fruits if "a" in x]

print(new_list)

['apple', 'banana', 'mango']


**Containers are packages of software that contain all of the necessary elements to run in any environment**

## python collection counter class:
##### https://docs.python.org/3/library/collections.html
##### This module implements specialized container datatypes providing alternatives to Python’s general purpose built-in containers, dict, list, set, and tuple.

#### path = "filepath" 

####  data = pd.read_csv(path+"name") or (f"{path}file_name")

#### data = pd.read_cav(path, sep= ":", encoding = 'utf-8' or 'latin' or any thin else)


# *******************************************

### for having a integrated view of all data frames:

#### for df in [name of all dataframes]
####           print(df.head())
####           print("+++++++++++++++++++++")

# **************************

### for combine some datasets: use merge()

### new_frame = pd.merge(pd.merge(old_dataframe1, old_dataframe2), old_dataframe3)

# +++++++++++++++++++++++++++++++++++++++

# Delete a part of data frame as a row or a column
## dataframe.drop("name of row of column" ,axis= zero or one, inplace = True of False)

# AXIS =0
### When the axis is set to zero while performing a specific action,
### the action is performed on rows that satisfy the condition.

# --------------

# AXIS=1
### When the axis is set to one while performing a specific action,
### the action is performed on **column**(s) that satisfy the condition

# +++++++++++++++++++++++++++++++++++++++++++

## What is inplace true and false in pandas?

### Explaining the Inplace Parameter for Beginners
### When inplace = True , the data is modified in place,
### which means it will return nothing and the dataframe is now updated.
### When inplace = False , which is the default,
### then the operation is performed and it returns a copy of the object.

# ++++++++++++++++++++++

## handy pandas methods

##### data.iloc: This command selects rows and columns by index. The index can be an integer, a list of integers, or a slice object.
##### data.loc: This command selects rows and columns by label. The label can be a string, a list of strings, or a dictionary.
##### data.at: This command selects a single value by label. The label can be a string or a list of strings.
##### data.ix: This command is a hybrid of data.loc and data.iloc and is deprecated in Pandas 1.0.0.
##### data.query: This command selects rows based on a Boolean expression. The Boolean expression can be any valid Python expression that evaluates to a Boolean value.
##### data.head(): This command returns the first few rows of the DataFrame. The number of rows to return is specified by the n parameter.
##### data.tail(): This command returns the last few rows of the DataFrame. The number of rows to return is specified by the n parameter.
##### data.sample(): This command returns a random sample of rows from the DataFrame. The number of rows to return is specified by the n parameter.
##### data.describe(): This command prints a summary of the DataFrame, including the mean, standard deviation, minimum, and maximum values.
##### data.info(): This command prints information about the DataFrame, including the number of rows and columns, the data types of the columns, and the missing values.

# ++++++++++++++++++++
# loc
#### https://www.youtube.com/watch?v=naRQyRZrXCE
#### https://www.w3schools.com/python/pandas/ref_df_iloc.asp



## df.loc[start_row: end_row , start_column : end_column]

## df.loc[[list of row indexs] ,  :] and revers for columns

## df.loc[ : , : ]

## df.loc[ : , "column name"]  get all rows of this column


## df.loc[ : , ["column name1 ", "column name2"]]  get all rows of this columns in a list

## df.loc[ : , "from column name 1" : "to column name 2" ]

## df.loc[ df.column name == "something", "another column name"]
### return a column with reletive values of another column



# ---------------------------------------------------------------------------------------

# * The loc and iloc functions in Pandas are used to slice a data set. 
# * The function .loc is primarily used for label indexing, while .
# * iloc is mainly used for integer indexing.

# ++++++++++++++++++++
# DATA ClEANING

## fill nan vlaues 
### filna(0, inplace = True) fill any nan values to 0

# +++++++++++++++++
## Create a new dataframe

### use this function:
#### https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html

### new = data.povit_table(data_frame, index="a column", column="some data", aggfunc=somthing)


### df.index[df >= 100]

# ++++++++++++++++++++++++++++++++++++++++

## to sort values: sort_values()
#### https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html

# ++++++++++++++++++++++++++++++++++++++++

## I have no idea about it

### https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.std.html
### df.groupby()[].std()

# +++++++++++++++++++++++++++++++
## Read data from csv 
#### https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
#### see what is index_col

# ++++++++++++++++++
## basics 
### df.shape() get shape of a table
### df.describe()
### df.column_name.describe()

# ++++++++++++++++++++++++++++++++
# clean dataset
## df.duplicated() 
## df.isnull()
## df.dropna(axis = 0 for row, how = "any", inplace = True)
## find out what datatype we are deal with:
## df.dtypes

# ++++++++++++++++++++++++++++++
## change columns name
## df.rename( columns = {"old name" : "new name"}, inplace = True)
# ++++++++++++++++++++++++++++
## edit data in columns and change data type
##### df['column_name'] = df.column_name.applye(lambda x: x.replace("old sing":"new sign").astype("int64")

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
## group values in a column
## df.groupby("column name").Title.count()

<!DOCTYPE html>
<html>
<head>
    <title>DataFrame Constructor Inputs</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Type</th>
            <th>Notes</th>
        </tr>
        <tr>
            <td>2D ndarray</td>
            <td>A matrix of data, passing optional row and column labels</td>
        </tr>
        <tr>
            <td>dict of arrays, lists, or tuples</td>
            <td>Each sequence becomes a column in the DataFrame. All sequences must be the same length.</td>
        </tr>
        <tr>
            <td>NumPy structured/record array</td>
            <td>Treated as the “dict of arrays” case</td>
        </tr>
        <tr>
            <td>dict of Series</td>
            <td>Each value becomes a column. Indexes from each Series are unioned together to form the result’s row index if no explicit index is passed.</td>
        </tr>
        <tr>
            <td>dict of dicts</td>
            <td>Each inner dict becomes a column. Keys are unioned to form the row index as in the “dict of Series” case.</td>
        </tr>
        <tr>
            <td>list of dicts or Series</td>
            <td>Each item becomes a row in the DataFrame. Union of dict keys or Series indexes become the DataFrame’s column labels.</td>
        </tr>
        <tr>
            <td>List of lists or tuples</td>
            <td>Treated as the “2D ndarray” case</td>
        </tr>
        <tr>
            <td>Another DataFrame</td>
            <td>The DataFrame’s indexes are used unless different ones are passed</td>
        </tr>
        <tr>
            <td>NumPy MaskedArray</td>
            <td>Like the “2D ndarray” case except masked values become NA/missing in the DataFrame result</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Main Index Objects in Pandas</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Class</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>Index</td>
            <td>The most general Index object, representing axis labels in a NumPy array of Python objects.</td>
        </tr>
        <tr>
            <td>Int64Index</td>
            <td>Specialized Index for integer values.</td>
        </tr>
        <tr>
            <td>MultiIndex</td>
            <td>“Hierarchical” index object representing multiple levels of indexing on a single axis. Can be thought of as similar to an array of tuples.</td>
        </tr>
        <tr>
            <td>DatetimeIndex</td>
            <td>Stores nanosecond timestamps (represented using NumPy’s datetime64 dtype).</td>
        </tr>
        <tr>
            <td>PeriodIndex</td>
            <td>Specialized Index for Period data (timespans).</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Index Methods and Properties</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Method</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>append</td>
            <td>Concatenate with additional Index objects, producing a new Index</td>
        </tr>
        <tr>
            <td>diff</td>
            <td>Compute set difference as an Index</td>
        </tr>
        <tr>
            <td>intersection</td>
            <td>Compute set intersection</td>
        </tr>
        <tr>
            <td>union</td>
            <td>Compute set union</td>
        </tr>
        <tr>
            <td>isin</td>
            <td>Compute boolean array indicating whether each value is contained in the passed collection</td>
        </tr>
        <tr>
            <td>delete</td>
            <td>Compute new Index with element at index i deleted</td>
        </tr>
        <tr>
            <td>drop</td>
            <td>Compute new index by deleting passed values</td>
        </tr>
        <tr>
            <td>insert</td>
            <td>Compute new Index by inserting element at index i</td>
        </tr>
        <tr>
            <td>is_monotonic</td>
            <td>Returns True if each element is greater than or equal to the previous element</td>
        </tr>
        <tr>
            <td>is_unique</td>
            <td>Returns True if the Index has no duplicate values</td>
        </tr>
        <tr>
            <td>unique</td>
            <td>Compute the array of unique values in the Index</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Indexing Options with DataFrame</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Type</th>
            <th>Notes</th>
        </tr>
        <tr>
            <td>obj[val]</td>
            <td>Select single column or sequence of columns from the DataFrame. Special case conveniences: boolean array (filter rows), slice (slice rows), or boolean DataFrame (set values based on some criterion).</td>
        </tr>
        <tr>
            <td>obj.ix[val]</td>
            <td>Selects single row of subset of rows from the DataFrame.</td>
        </tr>
        <tr>
            <td>obj.ix[:, val]</td>
            <td>Selects single column of subset of columns.</td>
        </tr>
        <tr>
            <td>obj.ix[val1, val2]</td>
            <td>Select both rows and columns.</td>
        </tr>
        <tr>
            <td>reindex method</td>
            <td>Conform one or more axes to new indexes.</td>
        </tr>
        <tr>
            <td>xs method</td>
            <td>Select single row or column as a Series by label.</td>
        </tr>
        <tr>
            <td>icol, irow methods</td>
            <td>Select single column or row, respectively, as a Series by integer location.</td>
        </tr>
        <tr>
            <td>get_value, set_value methods</td>
            <td>Select single value by row and column label.</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Flexible Arithmetic Methods</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Method</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>add</td>
            <td>Method for addition (+)</td>
        </tr>
        <tr>
            <td>sub</td>
            <td>Method for subtraction (-)</td>
        </tr>
        <tr>
            <td>div</td>
            <td>Method for division (/)</td>
        </tr>
        <tr>
            <td>mul</td>
            <td>Method for multiplication (*)</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Descriptive and Summary Statistics</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Method</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>count</td>
            <td>Number of non-NA values</td>
        </tr>
        <tr>
            <td>describe</td>
            <td>Compute set of summary statistics for Series or each DataFrame column</td>
        </tr>
        <tr>
            <td>min, max</td>
            <td>Compute minimum and maximum values</td>
        </tr>
        <tr>
            <td>argmin, argmax</td>
            <td>Compute index locations (integers) at which minimum or maximum value obtained, respectively</td>
        </tr>
        <tr>
            <td>idxmin, idxmax</td>
            <td>Compute index values at which minimum or maximum value obtained, respectively</td>
        </tr>
        <tr>
            <td>quantile</td>
            <td>Compute sample quantile ranging from 0 to 1</td>
        </tr>
        <tr>
            <td>sum</td>
            <td>Sum of values</td>
        </tr>
        <tr>
            <td>mean</td>
            <td>Mean of values</td>
        </tr>
        <tr>
            <td>median</td>
            <td>Arithmetic median (50% quantile) of values</td>
        </tr>
        <tr>
            <td>mad</td>
            <td>Mean absolute deviation from mean value</td>
        </tr>
        <tr>
            <td>var</td>
            <td>Sample variance of values</td>
        </tr>
        <tr>
            <td>std</td>
            <td>Sample standard deviation of values</td>
        </tr>
        <tr>
            <td>skew</td>
            <td>Sample skewness (3rd moment) of values</td>
        </tr>
        <tr>
            <td>kurt</td>
            <td>Sample kurtosis (4th moment) of values</td>
        </tr>
        <tr>
            <td>cumsum</td>
            <td>Cumulative sum of values</td>
        </tr>
        <tr>
            <td>cummin, cummax</td>
            <td>Cumulative minimum or maximum of values, respectively</td>
        </tr>
        <tr>
            <td>cumprod</td>
            <td>Cumulative product of values</td>
        </tr>
        <tr>
            <td>diff</td>
            <td>Compute 1st arithmetic difference (useful for time series)</td>
        </tr>
        <tr>
            <td>pct_change</td>
            <td>Compute percent changes</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Unique, Value Counts, and Binning Methods</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Method</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>isin</td>
            <td>Compute boolean array indicating whether each Series value is contained in the passed sequence of values.</td>
        </tr>
        <tr>
            <td>unique</td>
            <td>Compute array of unique values in a Series, returned in the order observed.</td>
        </tr>
        <tr>
            <td>value_counts</td>
            <td>Return a Series containing unique values as its index and frequencies as its values, ordered count in descending order.</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>NA Handling Methods</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Argument</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>dropna</td>
            <td>Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much missing data to tolerate.</td>
        </tr>
        <tr>
            <td>fillna</td>
            <td>Fill in missing data with some value or using an interpolation method such as 'ffill' or 'bfill'.</td>
        </tr>
        <tr>
            <td>isnull</td>
            <td>Return like-type object containing boolean values indicating which values are missing / NA.</td>
        </tr>
        <tr>
            <td>notnull</td>
            <td>Negation of isnull.</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>fillna Function Arguments</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Argument</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>value</td>
            <td>Scalar value or dict-like object to use to fill missing values.</td>
        </tr>
        <tr>
            <td>method</td>
            <td>Interpolation, by default 'ffill' if function called with no other arguments.</td>
        </tr>
        <tr>
            <td>axis</td>
            <td>Axis to fill on, default axis=0.</td>
        </tr>
        <tr>
            <td>inplace</td>
            <td>Modify the calling object without producing a copy.</td>
        </tr>
        <tr>
            <td>limit</td>
            <td>For forward and backward filling, maximum number of consecutive periods to fill.</td>
        </tr>
    </table>
</body>
</html>