<!DOCTYPE html>
<html>
<head>
<style>
  table {
    border-collapse: collapse;
    width: 100%;
  }

  th, td {
    border: 1px solid black;
    padding: 8px;
    text-align: left;
  }

  th {
    background-color: #f2f2f2;
  }
</style>
</head>
<body>

<h2>String Methods in Python</h2>

<table>
  <tr>
    <th>Row</th>
    <th>Method</th>
    <th>Description</th>
    <th>Example Usage</th>
  </tr>
  <tr>
    <td>1</td>
    <td><code>str.capitalize()</code></td>
    <td>Converts first character to uppercase.</td>
    <td><code>'hello world'.capitalize()</code> &rarr; "Hello world"</td>
  </tr>
  <tr>
    <td>2</td>
    <td><code>str.lower()</code></td>
    <td>Converts all characters to lowercase.</td>
    <td><code>'Hello World'.lower()</code> &rarr; "hello world"</td>
  </tr>
  <tr>
    <td>3</td>
    <td><code>str.upper()</code></td>
    <td>Converts all characters to uppercase.</td>
    <td><code>'Hello World'.upper()</code> &rarr; "HELLO WORLD"</td>
  </tr>
  <tr>
    <td>4</td>
    <td><code>str.title()</code></td>
    <td>Converts first char of each word to uppercase.</td>
    <td><code>'hello world'.title()</code> &rarr; "Hello World"</td>
  </tr>
  <tr>
    <td>5</td>
    <td><code>str.swapcase()</code></td>
    <td>Swaps case of each character.</td>
    <td><code>'Hello World'.swapcase()</code> &rarr; "hELLO wORLD"</td>
  </tr>
  <tr>
    <td>6</td>
    <td><code>str.strip()</code></td>
    <td>Removes leading and trailing whitespace.</td>
    <td><code>'  hello world  '.strip()</code> &rarr; "hello world"</td>
  </tr>
  <tr>
    <td>7</td>
    <td><code>str.lstrip()</code></td>
    <td>Removes leading whitespace.</td>
    <td><code>'  hello world  '.lstrip()</code> &rarr; "hello world  "</td>
  </tr>
  <tr>
    <td>8</td>
    <td><code>str.rstrip()</code></td>
    <td>Removes trailing whitespace.</td>
    <td><code>'  hello world  '.rstrip()</code> &rarr; "  hello world"</td>
  </tr>
  <tr>
    <td>9</td>
    <td><code>str.replace(old, new)</code></td>
    <td>Replaces occurrences of <em>old</em> with <em>new</em>.</td>
    <td><code>'Hello World'.replace('World', 'Python')</code> &rarr; "Hello Python"</td>
  </tr>
  <tr>
    <td>10</td>
    <td><code>str.startswith(prefix)</code></td>
    <td>Checks if string starts with <em>prefix</em>.</td>
    <td><code>'Hello World'.startswith('Hello')</code> &rarr; True</td>
  </tr>
  <tr>
    <td>11</td>
    <td><code>str.endswith(suffix)</code></td>
    <td>Checks if string ends with <em>suffix</em>.</td>
    <td><code>'Hello World'.endswith('World')</code> &rarr; True</td>
  </tr>
  <tr>
    <td>12</td>
    <td><code>str.find(sub)</code></td>
    <td>Returns lowest index of <em>sub</em>, or -1 if not found.</td>
    <td><code>'hello world'.find('world')</code> &rarr; 6</td>
  </tr>
  <tr>
    <td>13</td>
    <td><code>str.rfind(sub)</code></td>
    <td>Returns highest index of <em>sub</em>, or -1 if not found.</td>
    <td><code>'hello world'.rfind('l')</code> &rarr; 9</td>
  </tr>
  <tr>
    <td>14</td>
    <td><code>str.index(sub)</code></td>
    <td>Like <code>find()</code>, but raises exception if <em>sub</em> not found.</td>
    <td><code>'hello world'.index('world')</code> &rarr; 6</td>
  </tr>
  <tr>
    <td>15</td>
    <td><code>str.rindex(sub)</code></td>
    <td>Like <code>rfind()</code>, but raises exception if <em>sub</em> not found.</td>
    <td><code>'hello world'.rindex('l')</code> &rarr; 9</td>
  </tr>
  <tr>
    <td>16</td>
    <td><code>str.count(sub)</code></td>
    <td>Returns number of non-overlapping occurrences of <em>sub</em>.</td>
    <td><code>'hello world'.count('l')</code> &rarr; 3</td>
  </tr>
  <tr>
    <td>17</td>
    <td><code>str.join(iterable)</code></td>
    <td>Concatenates elements using separator.</td>
    <td><code>'-'.join(['a', 'b', 'c'])</code> &rarr; "a-b-c"</td>
  </tr>
  <tr>
    <td>18</td>
    <td><code>str.split(sep)</code></td>
    <td>Splits string into list at separator.</td>
    <td><code>'apple,banana,cherry'.split(',')</code> &rarr; ['apple', 'banana', 'cherry']</td>
  </tr>
  <tr>
    <td>19</td>
    <td><code>str.rsplit(sep)</code></td>
    <td>Splits string into list, starting from the right.</td>
    <td><code>'apple,banana,cherry'.rsplit(',', 1)</code> &rarr; ['apple,banana', 'cherry']</td>
  </tr>
  <tr>
    <td>20</td>
    <td><code>str.splitlines()</code></td>
    <td>Splits string at line breaks into list of lines.</td>
    <td><code>'Hello\nWorld'.splitlines()</code> &rarr; ['Hello', 'World']</td>
  </tr>
  <tr>
    <td>21</td>
    <td><code>str.center(width)</code></td>
    <td>Centers string within field of specified <em>width</em>.</td>
    <td><code>'hello'.center(10)</code> &rarr; "  hello   "</td>
  </tr>
  <tr>
    <td>22</td>
    <td><code>str.ljust(width)</code></td>
    <td>Left-justifies string within field of specified <em>width</em>.</td>
    <td><code>'hello'.ljust(10)</code> &rarr; "hello     "</td>
  </tr>
  <tr>
    <td>23</td>
    <td><code>str.rjust(width)</code></td>
    <td>Right-justifies string within field of specified <em>width</em>.</td>
    <td><code>'hello'.rjust(10)</code> &rarr; "     hello"</td>
  </tr>
  <tr>
    <td>24</td>
    <td><code>str.zfill(width)</code></td>
    <td>Pads numeric string with zeros on the left.</td>
    <td><code>'42'.zfill(5)</code> &rarr; "00042"</td>
  </tr>
</table>

</body>
</html>