<!DOCTYPE html>
<html>
<head>
<style>
  table {
    border-collapse: collapse;
    width: 100%;
  }
  th, td {
    border: 1px solid black;
    padding: 8px;
    text-align: left;
  }
</style>
</head>
<body>

<h2>NumPy Keyword Reference</h2>

<table>
  <tr>
    <th>Row</th>
    <th>Keyword</th>
    <th>Possible Values</th>
    <th>Goal</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>1</td>
    <td>np.array</td>
    <td>Array-like objects</td>
    <td>Create a NumPy array</td>
    <td>Convert input data to an array</td>
  </tr>
  <tr>
    <td>2</td>
    <td>np.zeros</td>
    <td>Shape, Data type</td>
    <td>Create an array filled with zeros</td>
    <td>Generate an array of zeros</td>
  </tr>
  <tr>
    <td>3</td>
    <td>np.ones</td>
    <td>Shape, Data type</td>
    <td>Create an array filled with ones</td>
    <td>Generate an array of ones</td>
  </tr>
  <tr>
    <td>4</td>
    <td>np.empty</td>
    <td>Shape, Data type</td>
    <td>Create an uninitialized array</td>
    <td>Generate an array with uninitialized values</td>
  </tr>
  <tr>
    <td>5</td>
    <td>np.arange</td>
    <td>Start, Stop, Step</td>
    <td>Create an array with a range of values</td>
    <td>Generate a sequence of values</td>
  </tr>
  <tr>
    <td>6</td>
    <td>np.linspace</td>
    <td>Start, Stop, Number of samples</td>
    <td>Create an array with linearly spaced values</td>
    <td>Generate evenly spaced values</td>
  </tr>
  <tr>
    <td>7</td>
    <td>np.logspace</td>
    <td>Start, Stop, Number of samples, Logarithmic scale</td>
    <td>Create an array with logarithmically spaced values</td>
    <td>Generate logarithmically spaced values</td>
  </tr>
  <tr>
    <td>8</td>
    <td>np.eye</td>
    <td>Number of rows</td>
    <td>Create a 2D identity matrix</td>
    <td>Generate a square identity matrix</td>
  </tr>
  <tr>
    <td>9</td>
    <td>np.random.rand</td>
    <td>Array shape</td>
    <td>Generate random numbers from a uniform distribution</td>
    <td>Generate random values between 0 and 1</td>
  </tr>
  <tr>
    <td>10</td>
    <td>np.random.randn</td>
    <td>Array shape</td>
    <td>Generate random numbers from a standard normal distribution</td>
    <td>Generate random values from a normal distribution with mean 0 and standard deviation 1</td>
  </tr>
  <tr>
    <td>11</td>
    <td>np.random.randint</td>
    <td>Low, High, Array shape</td>
    <td>Generate random integers</td>
    <td>Generate random integers within a specified range</td>
  </tr>
  <tr>
    <td>12</td>
    <td>np.reshape</td>
    <td>New shape</td>
    <td>Reshape an array</td>
    <td>Change the shape of an array</td>
  </tr>
  <tr>
    <td>13</td>
    <td>np.concatenate</td>
    <td>Sequence of arrays, Axis</td>
    <td>Join arrays along an axis</td>
    <td>Combine arrays along a specified axis</td>
  </tr>
  <tr>
    <td>14</td>
    <td>np.vstack</td>
    <td>Sequence of arrays</td>
    <td>Stack arrays vertically</td>
    <td>Stack arrays on top of each other</td>
  </tr>
  <tr>
    <td>15</td>
    <td>np.hstack</td>
    <td>Sequence of arrays</td>
    <td>Stack arrays horizontally</td>
    <td>Stack arrays side by side</td>
  </tr>
  <tr>
    <td>16</td>
    <td>np.split</td>
    <td>Array, Indices or sections</td>
    <td>Split an array into multiple sub-arrays</td>
    <td>Divide an array into smaller arrays</td>
  </tr>
  <tr>
    <td>17</td>
    <td>np.max</td>
    <td>Array</td>
    <td>Find the maximum value</td>
    <td>Return the maximum value in an array</td>
  </tr>
  <tr>
    <td>18</td>
    <td>np.min</td>
    <td>Array</td>
    <td>Find the minimum value</td>
    <td>Return the minimum value in an array</td>
  </tr>
  <tr>
    <td>19</td>
    <td>np.mean</td>
    <td>Array</td>
    <td>Calculate the mean</td>
    <td>Compute the arithmetic mean of an array</td>
  </tr>
  <tr>
    <td>20</td>
    <td>np.median</td>
    <td>Array</td>
    <td>Calculate the median</td>
    <td>Compute the median value of an array</td>
  </tr>
  <tr>
    <td>21</td>
    <td>np.std</td>
    <td>Array</td>
    <td>Calculate the standard deviation</td>
    <td>Compute the standard deviation of an array</td>
  </tr>
  <tr>
    <td>22</td>
    <td>np.var</td>
    <td>Array</td>
    <td>Calculate the variance</td>
    <td>Compute the variance of an array</td>
  </tr>
  <tr>
    <td>23</td>
    <td>np.dot</td>
    <td>Array, Array</td>
    <td>


  <tr>
    <td>23</td>
    <td>np.dot</td>
    <td>Array, Array</td>
    <td>Compute dot product</td>
    <td>Calculate the dot product of two arrays</td>
  </tr>
  <tr>
    <td>24</td>
    <td>np.cross</td>
    <td>Array, Array</td>
    <td>Compute cross product</td>
    <td>Calculate the cross product of two arrays</td>
  </tr>
  <tr>
    <td>25</td>
    <td>np.transpose</td>
    <td>Array</td>
    <td>Transpose an array</td>
    <td>Swap the rows and columns of an array</td>
  </tr>
  <tr>
    <td>26</td>
    <td>np.diagonal</td>
    <td>Array</td>
    <td>Extract diagonal elements</td>
    <td>Get the diagonal elements of an array</td>
  </tr>
  <tr>
    <td>27</td>
    <td>np.where</td>
    <td>Condition, [x, y]</td>
    <td>Find indices where condition is true</td>
    <td>Return indices that satisfy a condition</td>
  </tr>
  <tr>
    <td>28</td>
    <td>np.unique</td>
    <td>Array</td>
    <td>Find unique elements</td>
    <td>Get the unique elements of an array</td>
  </tr>
  <tr>
    <td>29</td>
    <td>np.argmax</td>
    <td>Array</td>
    <td>Find index of maximum value</td>
    <td>Return the index of the maximum value in an array</td>
  </tr>
  <tr>
    <td>30</td>
    <td>np.argmin</td>
    <td>Array</td>
    <td>Find index of minimum value</td>
    <td>Return the index of the minimum value in an array</td>
  </tr>
  <tr>
    <td>31</td>
    <td>np.any</td>
    <td>Array</td>
    <td>Test if any element is true</td>
    <td>Check if any element in the array evaluates to True</td>
  </tr>
  <tr>
    <td>32</td>
    <td>np.all</td>
    <td>Array</td>
    <td>Test if all elements are true</td>
    <td>Check if all elements in the array evaluate to True</td>
  </tr>
  <tr>
    <td>33</td>
    <td>np.save</td>
    <td>File name, Array</td>
    <td>Save array data to a binary file</td>
    <td>Write array data to a binary file</td>
  </tr>
  <tr>
    <td>34</td>
    <td>np.load</td>
    <td>File name</td>
    <td>Load array data from a binary file</td>
    <td>Read array data from a binary file</td>
  </tr>
  <tr>
    <td>35</td>
    <td>np.savetxt</td>
    <td>File name, Array</td>
    <td>Save array data to a text file</td>
    <td>Write array data to a text file</td>
  </tr>
  <tr>
    <td>36</td>
    <td>np.loadtxt</td>
    <td>File name</td>
    <td>Load array data from a text file</td>
    <td>Read array data from a text file</td>
  </tr>
  <tr>
    <td>37</td>
    <td>np.meshgrid</td>
    <td>X values, Y values</td>
    <td>Create coordinate grids</td>
    <td>Generate coordinate matrices for 2D plotting</td>
  </tr>
  <tr>
    <td>38</td>
    <td>np.gradient</td>
    <td>Array</td>
    <td>Calculate gradient</td>
    <td>Compute the gradient of an array</td>
  </tr>
  <tr>
    <td>39</td>
    <td>np.cov</td>
    <td>Array, Array</td>
    <td>Calculate covariance matrix</td>
    <td>Compute the covariance matrix of two arrays</td>
  </tr>
  <tr>
    <td>40</td>
    <td>np.corrcoef</td>
    <td>Array, Array</td><!-- ... (previous rows) ... -->

  <tr>
    <td>41</td>
    <td>np.loadtxt</td>
    <td>File name</td>
    <td>Load array data from a text file</td>
    <td>Read array data from a text file</td>
  </tr>
  <tr>
    <td>42</td>
    <td>np.meshgrid</td>
    <td>X values, Y values</td>
    <td>Create coordinate grids</td>
    <td>Generate coordinate matrices for 2D plotting</td>
  </tr>
  <tr>
    <td>43</td>
    <td>np.gradient</td>
    <td>Array</td>
    <td>Calculate gradient</td>
    <td>Compute the gradient of an array</td>
  </tr>
  <tr>
    <td>44</td>
    <td>np.cov</td>
    <td>Array, Array</td>
    <td>Calculate covariance matrix</td>
    <td>Compute the covariance matrix of two arrays</td>
  </tr>
  <tr>
    <td>45</td>
    <td>np.corrcoef</td>
    <td>Array, Array</td>
    <td>Calculate correlation coefficient</td>
    <td>Compute the correlation coefficient between two arrays</td>
  </tr>
  <tr>
    <td>46</td>
    <td>np.fft.fft</td>
    <td>Array</td>
    <td>Compute the one-dimensional discrete Fourier Transform</td>
    <td>Calculate the discrete Fourier Transform of an array</td>
  </tr>
  <tr>
    <td>47</td>
    <td>np.fft.ifft</td>
    <td>Array</td>
    <td>Compute the inverse one-dimensional discrete Fourier Transform</td>
    <td>Calculate the inverse discrete Fourier Transform of an array</td>
  </tr>
  <tr>
    <td>48</td>
    <td>np.fft.fftfreq</td>
    <td>Number of samples, Sample spacing</td>
    <td>Compute the frequencies for the FFT output</td>
    <td>Calculate the frequencies associated with the FFT output</td>
  </tr>
  <tr>
    <td>49</td>
    <td>np.polyfit</td>
    <td>x values, y values, Degree of polynomial</td>
    <td>Fit a polynomial to data</td>
    <td>Find the coefficients of a polynomial that fits given data</td>
  </tr>
  <tr>
    <td>50</td>
    <td>np.polyval</td>
    <td>Polynomial coefficients, x values</td>
    <td>Evaluate a polynomial at specific x values</td>
    <td>Calculate the values of a polynomial at given x values</td>
  </tr>
</table>

</body>
</html>
lation coefficient</td>
    <td>Compute the correlation coefficient between two arrays</td>
  </tr>
</table>

</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Array Creation Functions</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Function</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>array</td>
            <td>Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype. Copies the input data by default.</td>
        </tr>
        <tr>
            <td>asarray</td>
            <td>Convert input to ndarray, but do not copy if the input is already an ndarray.</td>
        </tr>
        <tr>
            <td>arange</td>
            <td>Like the built-in range but returns an ndarray instead of a list.</td>
        </tr>
        <tr>
            <td>ones, ones_like</td>
            <td>Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype.</td>
        </tr>
        <tr>
            <td>zeros, zeros_like</td>
            <td>Like ones and ones_like but producing arrays of 0’s instead.</td>
        </tr>
        <tr>
            <td>empty, empty_like</td>
            <td>Create new arrays by allocating new memory, but do not populate with any values like ones and zeros.</td>
        </tr>
        <tr>
            <td>eye, identity</td>
            <td>Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere).</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>NumPy Data Types</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Type</th>
            <th>Type Code</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>int8, uint8</td>
            <td>i1, u1</td>
            <td>Signed and unsigned 8-bit (1 byte) integer types</td>
        </tr>
        <tr>
            <td>int16, uint16</td>
            <td>i2, u2</td>
            <td>Signed and unsigned 16-bit integer types</td>
        </tr>
        <tr>
            <td>int32, uint32</td>
            <td>i4, u4</td>
            <td>Signed and unsigned 32-bit integer types</td>
        </tr>
        <tr>
            <td>int64, uint64</td>
            <td>i8, u8</td>
            <td>Signed and unsigned 64-bit integer types</td>
        </tr>
        <tr>
            <td>float16</td>
            <td>f2</td>
            <td>Half-precision floating point</td>
        </tr>
        <tr>
            <td>float32</td>
            <td>f4 or f</td>
            <td>Standard single-precision floating point. Compatible with C float</td>
        </tr>
        <tr>
            <td>float64, float128</td>
            <td>f8 or d</td>
            <td>Standard double-precision floating point. Compatible with C double and Python float object</td>
        </tr>
        <tr>
            <td>float128</td>
            <td>f16 or g</td>
            <td>Extended-precision floating point</td>
        </tr>
        <tr>
            <td>complex64, complex128, complex256</td>
            <td>c8, c16, c32</td>
            <td>Complex numbers represented by two 32, 64, or 128 floats, respectively</td>
        </tr>
        <tr>
            <td>bool</td>
            <td>?</td>
            <td>Boolean type storing True and False values</td>
        </tr>
        <tr>
            <td>object</td>
            <td>O</td>
            <td>Python object type</td>
        </tr>
        <tr>
            <td>string_</td>
            <td>S</td>
            <td>Fixed-length string type (1 byte per character). For example, to create a string dtype with length 10, use 'S10'.</td>
        </tr>
        <tr>
            <td>unicode_</td>
            <td>U</td>
            <td>Fixed-length Unicode type (number of bytes platform specific). Same specification semantics as string_ (e.g. 'U10').</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Unary Ufuncs</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Function</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>abs, fabs</td>
            <td>Compute the absolute value element-wise for integer, floating point, or complex values. Use fabs as a faster alternative for non-complex-valued data.</td>
        </tr>
        <tr>
            <td>sqrt</td>
            <td>Compute the square root of each element. Equivalent to arr ** 0.5</td>
        </tr>
        <tr>
            <td>square</td>
            <td>Compute the square of each element. Equivalent to arr ** 2</td>
        </tr>
        <tr>
            <td>exp</td>
            <td>Compute the exponent ex of each element</td>
        </tr>
        <tr>
            <td>log, log10, log2, log1p</td>
            <td>Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively</td>
        </tr>
        <tr>
            <td>sign</td>
            <td>Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)</td>
        </tr>
        <tr>
            <td>ceil</td>
            <td>Compute the ceiling of each element, i.e. the smallest integer greater than or equal to each element</td>
        </tr>
        <tr>
            <td>floor</td>
            <td>Compute the floor of each element, i.e. the largest integer less than or equal to each element</td>
        </tr>
        <tr>
            <td>rint</td>
            <td>Round elements to the nearest integer, preserving the dtype</td>
        </tr>
        <tr>
            <td>modf</td>
            <td>Return fractional and integral parts of array as separate array</td>
        </tr>
        <tr>
            <td>isnan</td>
            <td>Return boolean array indicating whether each value is NaN (Not a Number)</td>
        </tr>
        <tr>
            <td>isfinite, isinf</td>
            <td>Return boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively</td>
        </tr>
        <tr>
            <td>cos, cosh, sin, sinh, tan, tanh</td>
            <td>Regular and hyperbolic trigonometric functions</td>
        </tr>
        <tr>
            <td>arccos, arccosh, arcsin, arcsinh, arctan, arctanh</td>
            <td>Inverse trigonometric functions</td>
        </tr>
        <tr>
            <td>logical_not</td>
            <td>Compute truth value of not x element-wise. Equivalent to -arr.</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Binary Universal Functions</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Function</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>add</td>
            <td>Add corresponding elements in arrays</td>
        </tr>
        <tr>
            <td>subtract</td>
            <td>Subtract elements in second array from first array</td>
        </tr>
        <tr>
            <td>multiply</td>
            <td>Multiply array elements</td>
        </tr>
        <tr>
            <td>divide, floor_divide</td>
            <td>Divide or floor divide (truncating the remainder)</td>
        </tr>
        <tr>
            <td>power</td>
            <td>Raise elements in first array to powers indicated in second array</td>
        </tr>
        <tr>
            <td>maximum, fmax</td>
            <td>Element-wise maximum. fmax ignores NaN</td>
        </tr>
        <tr>
            <td>minimum, fmin</td>
            <td>Element-wise minimum. fmin ignores NaN</td>
        </tr>
        <tr>
            <td>mod</td>
            <td>Element-wise modulus (remainder of division)</td>
        </tr>
        <tr>
            <td>copysign</td>
            <td>Copy sign of values in second argument to values in first argument</td>
        </tr>
        <tr>
            <td>greater, greater_equal, less, less_equal, equal, not_equal</td>
            <td>Perform element-wise comparison, yielding boolean array. Equivalent to infix operators >, >=, <, <=, ==, !=</td>
        </tr>
        <tr>
            <td>logical_and, logical_or, logical_xor</td>
            <td>Compute element-wise truth value of logical operation. Equivalent to infix operators &, |, ^</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Basic Array Statistical Methods</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Method</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>sum</td>
            <td>Sum of all the elements in the array or along an axis. Zero-length arrays have sum 0.</td>
        </tr>
        <tr>
            <td>mean</td>
            <td>Arithmetic mean. Zero-length arrays have NaN mean.</td>
        </tr>
        <tr>
            <td>std, var</td>
            <td>Standard deviation and variance, respectively, with optional degrees of freedom adjustment (default denominator n).</td>
        </tr>
        <tr>
            <td>min, max</td>
            <td>Minimum and maximum.</td>
        </tr>
        <tr>
            <td>argmin, argmax</td>
            <td>Indices of minimum and maximum elements, respectively.</td>
        </tr>
        <tr>
            <td>cumsum</td>
            <td>Cumulative sum of elements starting from 0.</td>
        </tr>
        <tr>
            <td>cumprod</td>
            <td>Cumulative product of elements starting from 1.</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Array Set Operations</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Method</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>unique(x)</td>
            <td>Compute the sorted, unique elements in x</td>
        </tr>
        <tr>
            <td>intersect1d(x, y)</td>
            <td>Compute the sorted, common elements in x and y</td>
        </tr>
        <tr>
            <td>union1d(x, y)</td>
            <td>Compute the sorted union of elements</td>
        </tr>
        <tr>
            <td>in1d(x, y)</td>
            <td>Compute a boolean array indicating whether each element of x is contained in y</td>
        </tr>
        <tr>
            <td>setdiff1d(x, y)</td>
            <td>Set difference, elements in x that are not in y</td>
        </tr>
        <tr>
            <td>setxor1d(x, y)</td>
            <td>Set symmetric differences; elements that are in either of the arrays, but not both</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Numpy Linear Algebra Functions</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Function</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>diag</td>
            <td>Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal</td>
        </tr>
        <tr>
            <td>dot</td>
            <td>Matrix multiplication</td>
        </tr>
        <tr>
            <td>trace</td>
            <td>Compute the sum of the diagonal elements</td>
        </tr>
        <tr>
            <td>det</td>
            <td>Compute the matrix determinant</td>
        </tr>
        <tr>
            <td>eig</td>
            <td>Compute the eigenvalues and eigenvectors of a square matrix</td>
        </tr>
        <tr>
            <td>inv</td>
            <td>Compute the inverse of a square matrix</td>
        </tr>
        <tr>
            <td>pinv</td>
            <td>Compute the Moore-Penrose pseudo-inverse inverse of a square matrix</td>
        </tr>
        <tr>
            <td>qr</td>
            <td>Compute the QR decomposition</td>
        </tr>
        <tr>
            <td>svd</td>
            <td>Compute the singular value decomposition (SVD)</td>
        </tr>
        <tr>
            <td>solve</td>
            <td>Solve the linear system Ax = b for x, where A is a square matrix</td>
        </tr>
        <tr>
            <td>lstsq</td>
            <td>Compute the least-squares solution to y = Xb</td>
        </tr>
    </table>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Numpy Random Functions</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>Function</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>seed</td>
            <td>Seed the random number generator</td>
        </tr>
        <tr>
            <td>permutation</td>
            <td>Return a random permutation of a sequence, or return a permuted range</td>
        </tr>
        <tr>
            <td>shuffle</td>
            <td>Randomly permute a sequence in place</td>
        </tr>
        <tr>
            <td>rand</td>
            <td>Draw samples from a uniform distribution</td>
        </tr>
        <tr>
            <td>randint</td>
            <td>Draw random integers from a given low-to-high range</td>
        </tr>
        <tr>
            <td>randn</td>
            <td>Draw samples from a normal distribution with mean 0 and standard deviation 1 (MATLAB-like interface)</td>
        </tr>
        <tr>
            <td>binomial</td>
            <td>Draw samples from a binomial distribution</td>
        </tr>
        <tr>
            <td>normal</td>
            <td>Draw samples from a normal (Gaussian) distribution</td>
        </tr>
        <tr>
            <td>beta</td>
            <td>Draw samples from a beta distribution</td>
        </tr>
        <tr>
            <td>chisquare</td>
            <td>Draw samples from a chi-square distribution</td>
        </tr>
        <tr>
            <td>gamma</td>
            <td>Draw samples from a gamma distribution</td>
        </tr>
        <tr>
            <td>uniform</td>
            <td>Draw samples from a uniform [0, 1) distribution</td>
        </tr>
    </table>
</body>
</html>